"""Daily report generation.

One hard rule: the report states the provenance of its own numbers. If the
figures came from seed or simulated data, every financial section is prefixed
with an unmissable banner. A polished report of imaginary revenue is not a
neutral placeholder — it is the thing most likely to cause a bad real-world
decision, and it is trivially mistaken for the real thing a week later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path
from typing import Any

from .config import Policy
from .inventory import InventoryPlan, portfolio_health
from .models import money
from .risk import SpendState, preflight_report
from .store import Store, learning_summary


@dataclass
class ReportContext:
    """Everything the report needs, plus where it all came from."""

    report_date: str
    data_source: str                      # live | seed | mixed | none
    metrics: list[dict[str, Any]] = field(default_factory=list)
    prior_metrics: list[dict[str, Any]] = field(default_factory=list)
    inventory_plans: list[InventoryPlan] = field(default_factory=list)
    ad_summary: dict[str, Any] = field(default_factory=dict)
    ad_actions: list[Any] = field(default_factory=list)
    opportunities: list[Any] = field(default_factory=list)
    review_insights: list[Any] = field(default_factory=list)
    price_recommendations: list[Any] = field(default_factory=list)
    spend_state: SpendState = field(default_factory=SpendState)
    connector_status: list[dict[str, Any]] = field(default_factory=list)
    # Charter additions
    account_health: Any = None
    capital_state: Any = None
    allocation_decisions: list[Any] = field(default_factory=list)
    allocation_notes: list[str] = field(default_factory=list)
    concentration: dict[str, Any] = field(default_factory=dict)
    turns: dict[str, Any] = field(default_factory=dict)
    supplier_alerts: list[Any] = field(default_factory=list)
    signal_coverage_pct: float = 0.0
    unavailable_signals: list[str] = field(default_factory=list)


def _totals(rows: list[dict[str, Any]]) -> dict[str, float]:
    return {
        "revenue": money(sum(r.get("revenue", 0.0) for r in rows)),
        "cogs": money(sum(r.get("cogs", 0.0) for r in rows)),
        "fees": money(sum(r.get("fees", 0.0) for r in rows)),
        "ad_spend": money(sum(r.get("ad_spend", 0.0) for r in rows)),
        "refunds": money(sum(r.get("refunds", 0.0) for r in rows)),
        "net_profit": money(sum(r.get("net_profit", 0.0) for r in rows)),
        "units": sum(int(r.get("units", 0)) for r in rows),
    }


def _delta_line(label: str, today: float, prior: float, *, currency: bool = True) -> str:
    fmt = (lambda v: f"${v:,.2f}") if currency else (lambda v: f"{v:,.0f}")
    if prior == 0:
        return f"| {label} | {fmt(today)} | — | — |"
    delta = today - prior
    pct = delta / abs(prior) * 100
    arrow = "▲" if delta > 0 else ("▼" if delta < 0 else "—")
    return f"| {label} | {fmt(today)} | {fmt(prior)} | {arrow} {pct:+.1f}% |"


def build_daily_report(policy: Policy, ctx: ReportContext, store: Store | None = None) -> str:
    p: list[str] = []
    biz = policy.meta.get("business_name", "Store")

    p.append(f"# Daily Operations Report — {ctx.report_date}")
    p.append(f"**{biz}** · generated by the autonomous operator")
    p.append("")

    # ---- provenance banner (never suppressed) ---------------------------
    if ctx.data_source != "live":
        p.append("> ## ⚠️ THESE ARE NOT REAL BUSINESS NUMBERS")
        p.append(">")
        p.append(
            f"> Data source: **{ctx.data_source.upper()}**. No marketplace credentials "
            "are configured, so no live sales, inventory, or ad data could be read. "
            "Every financial figure below is derived from seed data and exists only to "
            "demonstrate that the pipeline works end to end."
        )
        p.append(">")
        p.append(
            "> **Do not make purchasing, pricing, or advertising decisions from this "
            "report.** Connect the marketplaces (`operator status`) and regenerate."
        )
        p.append("")

    mode = "LIVE EXECUTION" if policy.live_trading_enabled else "ADVISORY ONLY"
    p.append(f"**Operating mode:** {mode}")
    p.append("")

    # ---- P&L -------------------------------------------------------------
    p.append("## 1. Revenue & Profit")
    if not ctx.metrics:
        p.append("_No sales data available for this date._")
    else:
        t = _totals(ctx.metrics)
        prior = _totals(ctx.prior_metrics) if ctx.prior_metrics else {}
        p.append("| Metric | Today | Prior period | Change |")
        p.append("|---|---:|---:|---:|")
        for label, key in [
            ("Revenue", "revenue"), ("COGS", "cogs"), ("Marketplace fees", "fees"),
            ("Ad spend", "ad_spend"), ("Refunds", "refunds"), ("**Net profit**", "net_profit"),
        ]:
            p.append(_delta_line(label, t[key], prior.get(key, 0.0)))
        p.append(_delta_line("Units sold", t["units"], prior.get("units", 0.0), currency=False))
        p.append("")
        if t["revenue"] > 0:
            gross_profit = money(t["revenue"] - t["cogs"])
            gross_margin = gross_profit / t["revenue"] * 100
            net_margin = t["net_profit"] / t["revenue"] * 100
            tacos = t["ad_spend"] / t["revenue"] * 100
            tax_rate = float(policy.tax["income_tax_rate_pct"])
            after_tax = money(t["net_profit"] * (1 - tax_rate / 100)) if t["net_profit"] > 0 \
                else t["net_profit"]

            p.append(f"- Gross profit: **${gross_profit:,.2f}** ({gross_margin:.1f}% gross margin)")
            p.append(f"- Net margin: **{net_margin:.1f}%**")
            p.append(
                f"- **After-tax profit: ${after_tax:,.2f}** at a {tax_rate:.0f}% planning "
                "rate — this is the charter's KPI, not the pre-tax line above."
            )
            p.append(
                f"- TACOS (total ad spend / total revenue): **{tacos:.1f}%** — the number "
                "that matters more than campaign ACOS, because it includes the sales ads "
                "did not cause."
            )
            p.append(
                f"- Operating cash movement: **${money(t['net_profit'] - t['refunds']):,.2f}** "
                "before inventory purchases. Profit is not cash: goods are paid for "
                "months before the marketplace settles the sale."
            )
        p.append("")

    # ---- advertising -----------------------------------------------------
    p.append("## 2. Advertising")
    if not ctx.ad_summary:
        p.append("_No campaign data available._")
    else:
        s = ctx.ad_summary
        p.append(f"- Spend: **${s.get('total_spend', 0):,.2f}** → ad sales **${s.get('total_ad_sales', 0):,.2f}**")
        p.append(f"- Blended ACOS: **{s.get('blended_acos_pct', 0):.1f}%** · ROAS **{s.get('blended_roas', 0):.2f}x**")
        p.append(f"- Campaigns: {s.get('campaigns', 0)} · to scale: {s.get('to_scale', 0)} · to pause: {s.get('to_pause', 0)}")
        p.append("")
        if ctx.ad_actions:
            p.append("**Recommended ad actions**")
            p.append("")
            p.append("| Target | Action | From | To | Why |")
            p.append("|---|---|---:|---:|---|")
            for a in ctx.ad_actions[:10]:
                p.append(
                    f"| {a.target} | {a.action} | {a.current_value:.2f} | "
                    f"{a.proposed_value:.2f} | {a.rationale} |"
                )
            p.append("")

    # ---- inventory -------------------------------------------------------
    p.append("## 3. Inventory Health")
    if not ctx.inventory_plans:
        p.append("_No inventory data available._")
    else:
        h = portfolio_health(ctx.inventory_plans)
        p.append(
            f"Health score **{h['health_score']}/100** across {h['skus']} SKUs — "
            f"{h['healthy']} healthy · {h['reorder_now']} reorder · {h['critical']} critical · "
            f"{h['overstock']} overstock · {h['stalled']} stalled"
        )
        p.append("")
        p.append("| SKU | Status | On hand | Velocity | Cover | Stockout in | Reorder | Cost |")
        p.append("|---|---|---:|---:|---:|---:|---:|---:|")
        for plan in ctx.inventory_plans:
            cover = "∞" if plan.days_of_cover == float("inf") else f"{plan.days_of_cover:.0f}d"
            so = f"{plan.stockout_date_days:.0f}d" if plan.stockout_date_days is not None else "—"
            p.append(
                f"| {plan.sku} | {plan.status} | {plan.on_hand_units} | "
                f"{plan.daily_velocity:.1f}/d | {cover} | {so} | "
                f"{plan.recommended_order_units or '—'} | "
                f"{'$' + format(plan.estimated_order_cost, ',.2f') if plan.estimated_order_cost else '—'} |"
            )
        p.append("")
        urgent = [x for x in ctx.inventory_plans if x.status in ("CRITICAL", "REORDER_NOW")]
        if urgent:
            p.append("**Urgent inventory notes**")
            p.append("")
            for plan in urgent[:5]:
                p.append(f"- **{plan.sku}** — {plan.rationale[-1]}")
            p.append("")

    # ---- best / worst ----------------------------------------------------
    p.append("## 4. Best & Worst Performers")
    if not ctx.metrics:
        p.append("_No sales data available._")
    else:
        n_best = int(policy.reporting.get("top_n_products", 5))
        n_worst = int(policy.reporting.get("worst_n_products", 5))
        ranked = sorted(ctx.metrics, key=lambda r: r.get("net_profit", 0.0), reverse=True)

        p.append(f"**Top {n_best} by net profit**")
        p.append("")
        p.append("| SKU | Marketplace | Units | Revenue | Net profit | Margin |")
        p.append("|---|---|---:|---:|---:|---:|")
        for r in ranked[:n_best]:
            m = (r["net_profit"] / r["revenue"] * 100) if r.get("revenue") else 0
            p.append(
                f"| {r['sku']} | {r['marketplace']} | {r['units']} | "
                f"${r['revenue']:,.2f} | ${r['net_profit']:,.2f} | {m:.1f}% |"
            )
        p.append("")
        losers = [r for r in ranked if r.get("net_profit", 0) <= 0] or ranked[-n_worst:]
        p.append(f"**Bottom {min(n_worst, len(losers))} — these need a decision**")
        p.append("")
        p.append("| SKU | Marketplace | Units | Revenue | Net profit | Ad spend |")
        p.append("|---|---|---:|---:|---:|---:|")
        for r in reversed(losers[-n_worst:]):
            p.append(
                f"| {r['sku']} | {r['marketplace']} | {r['units']} | ${r['revenue']:,.2f} | "
                f"${r['net_profit']:,.2f} | ${r.get('ad_spend', 0):,.2f} |"
            )
        p.append("")

    # ---- pricing ---------------------------------------------------------
    if ctx.price_recommendations:
        p.append("## 5. Pricing Actions")
        p.append("")
        p.append("| SKU | Now | Recommend | Change | Floor | Margin | Action | Approval |")
        p.append("|---|---:|---:|---:|---:|---:|---|---|")
        for r in ctx.price_recommendations:
            p.append(
                f"| {r.sku} | ${r.current_price:.2f} | ${r.recommended_price:.2f} | "
                f"{r.change_pct:+.1f}% | ${r.floor_price:.2f} | "
                f"{r.projected_margin_pct:.1f}% | {r.action} | "
                f"{'YES' if r.requires_approval else 'auto'} |"
            )
        p.append("")

    # ---- reviews ---------------------------------------------------------
    if ctx.review_insights:
        p.append("## 6. Customer Reviews")
        p.append("")
        for ins in ctx.review_insights:
            flag = " 🚨" if ins.severity.value == "CRITICAL" else ""
            p.append(
                f"**{ins.sku}**{flag} — {ins.average_rating:.2f}★ across "
                f"{ins.total_reviews} reviews ({ins.negative_pct:.0f}% negative)"
            )
            if ins.top_complaint:
                p.append(f"- Dominant complaint theme: `{ins.top_complaint}`")
            for a in ins.recommended_actions:
                p.append(f"- {a}")
            p.append("")

    # ---- opportunities ---------------------------------------------------
    p.append("## 7. New Opportunities")
    if not ctx.opportunities:
        p.append("_No candidates screened this cycle._")
    else:
        p.append("| SKU | Decision | Score | ROI | Margin | Blocking reason |")
        p.append("|---|---|---:|---:|---:|---|")
        for r in ctx.opportunities[:10]:
            e = r.economics
            reason = "—" if not r.blocking_failures else r.blocking_failures[0].detail[:90]
            p.append(
                f"| {r.sku} | {r.decision.value} | {r.score:.0f} | "
                f"{e.roi_pct:.0f}% | {e.margin_pct:.0f}% | {reason} |"
            )
        p.append("")

    # ---- account health --------------------------------------------------
    p.append("## 8. Account Health")
    if ctx.account_health is None:
        p.append(
            "_No account health metrics supplied._ These are not assumed healthy — "
            "an unmeasured defect rate is exactly how a suspension arrives without "
            "warning. Wire the Amazon performance metrics before scaling anything."
        )
    else:
        ah = ctx.account_health
        icon = {"CRITICAL": "🚨", "WARN": "⚠️", "INFO": "✓"}.get(ah.severity.value, "")
        p.append(f"{icon} **{ah.severity.value}** · {ah.coverage_pct:.0f}% of metrics measured")
        p.append("")
        p.append("| Metric | Value | Limit | Utilisation |")
        p.append("|---|---:|---:|---:|")
        for m in ah.metrics:
            value = f"{m.value:g}{m.unit}" if m.known else "unknown"
            util = f"{m.utilisation_pct:.0f}%" if m.utilisation_pct is not None else "—"
            p.append(f"| {m.label} | {value} | {m.limit:g}{m.unit} | {util} |")
        p.append("")
        for a in ah.actions:
            p.append(f"- {a}")
        p.append("")

    # ---- capital ---------------------------------------------------------
    p.append("## 9. Capital & Allocation")
    if ctx.capital_state is None:
        p.append("_No capital position supplied._")
    else:
        from .capital import reserves
        res = reserves(policy)
        cs = ctx.capital_state
        p.append(f"- Total capital: **${cs.total_capital_usd:,.2f}** · "
                 f"deployed **${cs.deployed_usd:,.2f}** · "
                 f"cash **${cs.cash_available_usd:,.2f}**")
        p.append(f"- Reserves held: ${res['total']:,.2f} "
                 f"(ads ${res['advertising']:,.2f} · refunds ${res['refunds']:,.2f} · "
                 f"contingency ${res['contingency']:,.2f})")
        p.append(f"- Deployable now: **${res['deployable']:,.2f}**")
        p.append("")

        if ctx.turns:
            tn = ctx.turns
            p.append(f"**Inventory turns: {tn['portfolio_turns']:.2f}/yr** "
                     f"(target {tn['target_turns']:.1f}, floor {tn['min_turns']:.1f}) — "
                     "the multiplier on margin. The same 30% margin earns four times "
                     "as much at 4 turns as at 1.")
            if tn["sluggish"]:
                p.append(f"- Below floor: {', '.join(tn['sluggish'])} "
                         f"(${tn['capital_in_sluggish']:,.2f} tied up)")
            if tn["dead"]:
                p.append(f"- Not moving at all: {', '.join(tn['dead'])} "
                         f"(${tn['capital_in_dead']:,.2f} dead capital)")
            p.append("")

        if ctx.concentration and ctx.concentration.get("breaches"):
            p.append("**⚠️ Concentration limits breached**")
            p.append("")
            for b in ctx.concentration["breaches"]:
                p.append(f"- {b['dimension']} `{b['value']}` holds {b['share_pct']:.0f}% "
                         f"of deployed capital (limit {b['limit_pct']:.0f}%)")
            p.append("")
            p.append("A good margin does not offset concentration risk. One suspension, "
                     "patent claim, or supplier failure at this weighting is fatal.")
            p.append("")

        if ctx.allocation_decisions:
            p.append("**Capital allocation this cycle**")
            p.append("")
            p.append("| Rank | SKU | Requested | Funded | Headline ROI | Risk-adj | Annualised |")
            p.append("|---:|---|---:|---:|---:|---:|---:|")
            for d in ctx.allocation_decisions:
                p.append(
                    f"| {d.rank} | {d.request.sku} | ${d.request.amount_usd:,.0f} | "
                    f"${d.approved_amount:,.0f} | {d.request.expected_roi_pct:.0f}% | "
                    f"{d.risk_adjusted_roi_pct:.0f}% | {d.annualised_roi_pct:.0f}% |"
                )
            p.append("")
            for d in ctx.allocation_decisions:
                if d.reasons:
                    p.append(f"- **{d.request.sku}**: {d.reasons[0]}")
                    for r in d.reasons[1:]:
                        p.append(f"  - {r}")
            p.append("")
        for note in ctx.allocation_notes:
            p.append(f"- {note}")
        p.append("")

    # ---- supplier alerts -------------------------------------------------
    if ctx.supplier_alerts:
        p.append("## 10. Supplier Alerts")
        p.append("")
        for a in ctx.supplier_alerts:
            p.append(f"- **[{a.severity}] {a.supplier_name}** — {a.detail}")
            p.append(f"  - {a.recommendation}")
        p.append("")

    # ---- signal coverage -------------------------------------------------
    p.append("## 11. Market Signal Coverage")
    p.append(
        f"**{ctx.signal_coverage_pct:.0f}% of the weighted signal set is observable.** "
        "Confidence scores and opportunity rankings are only as good as this number."
    )
    p.append("")
    if ctx.unavailable_signals:
        p.append("Not connected:")
        p.append("")
        for line in ctx.unavailable_signals:
            p.append(f"- {line}")
        p.append("")
        p.append(
            "These are reported as unavailable, never estimated. A guessed trend "
            "signal survives into a purchase order and becomes inventory."
        )
    p.append("")

    # ---- risk ------------------------------------------------------------
    p.append("## 12. Risk & Capital Position")
    for line in preflight_report(policy, ctx.spend_state):
        p.append(f"- {line}")
    p.append("")

    if ctx.connector_status:
        unconfigured = [c for c in ctx.connector_status if not c["configured"]]
        if unconfigured:
            p.append("**Marketplace connections not configured**")
            p.append("")
            for c in unconfigured:
                p.append(f"- `{c['marketplace']}` — missing: {', '.join(c['missing_env'])}")
            p.append("")

    # ---- actions ---------------------------------------------------------
    p.append("## 13. Recommended Actions")
    actions = _collect_actions(policy, ctx)
    if not actions:
        p.append("_No actions required today._")
    else:
        for i, (priority, text) in enumerate(actions, 1):
            p.append(f"{i}. **[{priority}]** {text}")
    p.append("")

    # ---- learning --------------------------------------------------------
    if store is not None:
        p.append("## 14. Decision Journal")
        ls = learning_summary(store)
        p.append(
            f"- Decisions recorded: **{ls['total_decisions']}** "
            f"({ls['resolved_decisions']} with known outcomes, "
            f"{ls['unresolved_decisions']} still open)"
        )
        for domain, stats in ls["by_domain"].items():
            p.append(
                f"- `{domain}`: {stats['as_expected']}/{stats['resolved']} met expectation "
                f"({stats['hit_rate_pct']}%)"
            )
        p.append(f"- _{ls['note']}_")
        pending = store.pending_approvals()
        if pending:
            p.append("")
            p.append(f"**{len(pending)} action(s) awaiting your approval**")
            p.append("")
            for d in pending[:10]:
                p.append(f"- `{d['action_id']}` [{d['domain']}] {d['sku']}: {d['action']}")
            p.append("")
            p.append("Approve with: `python -m operator_core.cli approve <action_id> --by \"<name>\"`")
        p.append("")

    p.append("---")
    p.append(
        "_Generated by the autonomous ecommerce operator. Recommendations are produced "
        "from the rules in `config/policy.toml`; nothing above was executed against a "
        "live account._"
    )
    return "\n".join(p)


def _collect_actions(policy: Policy, ctx: ReportContext) -> list[tuple[str, str]]:
    """Rank the day's work by what actually costs money if ignored."""
    actions: list[tuple[str, str]] = []

    for ins in ctx.review_insights:
        if ins.account_risk_hits:
            actions.append((
                "CRITICAL",
                f"{ins.sku}: {len(ins.account_risk_hits)} review(s) contain safety or "
                "counterfeit language. Read them today — this is the category of issue "
                "that ends with a suspended account.",
            ))

    for plan in ctx.inventory_plans:
        if plan.status == "CRITICAL":
            actions.append((
                "CRITICAL",
                f"{plan.sku}: stockout in ~{plan.stockout_date_days:.0f} days against a "
                f"{plan.reorder_point_units}-unit reorder point. "
                f"Order {plan.recommended_order_units} units "
                f"(${plan.estimated_order_cost:,.2f})"
                + (" — needs your approval." if plan.requires_approval else "."),
            ))

    for a in ctx.ad_actions:
        if a.action == "PAUSE":
            actions.append((
                "HIGH",
                f"Pause `{a.target}` — {a.rationale} Saves roughly "
                f"${a.projected_monthly_impact:,.2f}/month.",
            ))

    for r in ctx.price_recommendations:
        if r.action == "BLOCKED_BY_FLOOR":
            actions.append((
                "HIGH",
                f"{r.sku} is pinned at its ${r.floor_price:.2f} profit floor while rivals "
                "sit lower. Either reduce landed cost or differentiate — do not chase "
                "the price down.",
            ))

    for plan in ctx.inventory_plans:
        if plan.status == "REORDER_NOW":
            actions.append((
                "MEDIUM",
                f"{plan.sku}: reorder {plan.recommended_order_units} units "
                f"(${plan.estimated_order_cost:,.2f}).",
            ))
        elif plan.status == "OVERSTOCK":
            actions.append((
                "MEDIUM",
                f"{plan.sku}: {plan.days_of_cover:.0f} days of cover is dead capital. "
                "Promote or bundle it down.",
            ))
        elif plan.status == "STALLED":
            actions.append((
                "MEDIUM",
                f"{plan.sku}: zero velocity with {plan.on_hand_units} units on hand. "
                "Diagnose visibility and price before writing it off.",
            ))

    for a in ctx.ad_actions:
        if a.action in ("INCREASE_BUDGET", "HARVEST"):
            actions.append((
                "MEDIUM",
                f"{a.action.title().replace('_', ' ')} on `{a.target}`: {a.rationale}",
            ))

    approved = [o for o in ctx.opportunities if o.decision.value == "NEEDS_HUMAN_APPROVAL"]
    if approved:
        top = approved[0]
        actions.append((
            "MEDIUM",
            f"Review sourcing candidate `{top.sku}` — passed every gate at "
            f"{top.economics.roi_pct:.0f}% ROI / {top.economics.margin_pct:.0f}% margin "
            f"(opportunity score {top.score:.0f}).",
        ))

    if ctx.data_source != "live":
        actions.append((
            "CRITICAL",
            "Connect marketplace credentials. Until then every number in this report is "
            "seed data and the operator cannot manage anything real.",
        ))

    order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    actions.sort(key=lambda x: order.get(x[0], 9))
    return actions


def write_report(policy: Policy, content: str, report_date: str) -> Path:
    out_dir = Path(policy.reporting.get("output_dir", "reports"))
    if not out_dir.is_absolute():
        out_dir = Path(__file__).resolve().parent.parent / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"daily-report-{report_date}.md"
    path.write_text(content, encoding="utf-8")
    return path


def prior_period_dates(report_date: str, days: int = 1) -> str:
    d = date.fromisoformat(report_date) - timedelta(days=days)
    return d.isoformat()
